# Generated by Django 5.0 on 2024-03-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_docs', '0003_alter_documentation_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='regex_url',
            field=models.CharField(blank=True, help_text="Regular expression to match the URL of the page you are documenting, if any. Leave blank if this isn't needed.", max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicaldocumentation',
            name='regex_url',
            field=models.CharField(blank=True, db_index=True, help_text="Regular expression to match the URL of the page you are documenting, if any. Leave blank if this isn't needed.", max_length=200, null=True),
        ),
    ]
