title: Django Easy Docs
description: >-
  A simple, opinionated way to add documentation to your website. 
  Add a "Help" button to any page, and intuitively build the documentation for your Django app.

baseurl: "/django-easy-docs" 
url: "https://lewisfletcher.github.io"
lang: "en"
github_username:  LewisFletcher

readme_index:
  with_frontmatter: true

mathjax: {}

# Build settings
remote_theme: rundocs/jekyll-rtd-theme
plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
